import { Palette, StyleMetrics, Switch, Button, LineEdit } from "std-widgets.slint";
import { Settings, Theme } from "settings.slint";

export { Settings, SettingsUi, Theme } from "settings.slint";

export component AppUi inherits Window {
    public function reload-theme() {
        if (Settings.theme == Theme.dark) {
            Palette.color-scheme = ColorScheme.dark;
        } else if (Settings.theme == Theme.light) {
            Palette.color-scheme = ColorScheme.light;
        } else {
            Palette.color-scheme = ColorScheme.unknown;
        }
    }

    callback open-settings <=> settings-button.clicked;

    title: "Youkoso";
    preferred-width: 800px;
    preferred-height: 600px;

    Image {
        source: @image-url("icons/settings-symbolic.svg");
        colorize: Palette.control-foreground;
        x: parent.width - self.width - self.padding;
        y: self.padding;
        width: 40px;
        height: 40px;
        padding: StyleMetrics.layout-padding;

        settings-button := TouchArea {}
    }

    LineEdit {
        text: "";
        placeholder-text: "Enter RFID";
        width: 250px;
        height: 40px;
    }
}