import { LineEdit, Palette, StyleMetrics } from "std-widgets.slint";
import { Settings, SettingsPage, Theme } from "settings.slint";

export { Settings, Theme } from "settings.slint";

enum Page {
    home,
    settings,
}

component HomePage {
    width: 800px;
    height: 600px;

    callback open-settings;

    Image {
        source: @image-url("icons/settings-symbolic.svg");
        colorize: Palette.control-foreground;
        x: root.width - self.width - self.padding;
        y: self.padding;
        width: 40px;
        height: 40px;
        padding: StyleMetrics.layout-padding;

        TouchArea {
            clicked => {
                open-settings();
            }
        }
    }

    LineEdit {
        text: "";
        placeholder-text: "Enter ID";
        width: 250px;
        height: 40px;
    }
}

export component App inherits Window {
    public function reload-theme() {
        if Settings.theme == Theme.dark {
            Palette.color-scheme = ColorScheme.dark;
        } else if Settings.theme == Theme.light {
            Palette.color-scheme = ColorScheme.light;
        } else {
            Palette.color-scheme = ColorScheme.unknown;
        }
    }

    in-out property <Page> currentPage: home;
    property <float> home-opacity: 1;
    animate home-opacity {
        duration: 200ms;
        easing: ease-in-out;
    }
    property <float> settings-opacity: 0;
    animate settings-opacity {
        duration: 200ms;
        easing: ease-in-out;
    }

    title: {
        if currentPage == Page.settings {
            return "Youkoso - Settings";
        } else {
            return "Youkoso";
        }
    }
    preferred-width: 800px;
    preferred-height: 600px;

    HomePage {
        width: 100%;
        height: 100%;
        opacity: home-opacity;
        visible: home-opacity > 0;

        open-settings => {
            currentPage = Page.settings;
            home-opacity = 0;
            settings-opacity = 1;
        }
    }

    SettingsPage {
        width: 100%;
        height: 100%;
        opacity: settings-opacity;
        visible: settings-opacity > 0;

        init => {
            self.focus();
        }

        close => {
            currentPage = Page.home;
            home-opacity = 1;
            settings-opacity = 0;
        }
    }
}
