import {
    Button,
    ComboBox,
    GridBox,
    HorizontalBox,
    LineEdit,
    Palette,
    ScrollView,
    StandardButton,
    StyleMetrics,
} from "std-widgets.slint";

export struct MyStudio {
    email: string,
    company_id: string,
}
export struct StudentData {
    filepath: string,
    sheet-name: string,
    name-column: int,
    id-column: int,
    immediate-sign-in-column: int,
    immediate-sign-in-enabled-symbol: string,
}
export global Settings {
    in-out property <bool> syncing: false;
    callback sync-settings;

    callback reset(string);
    callback reset-all;

    in-out property <MyStudio> my-studio;
    in-out property <StudentData> student-data;
}

component Separator {
    in property <Orientation> orientation: horizontal;
    property <length> overall-thickness: max(10px, 1phx);
    property <length> line-thickness: max(1.2px, 1phx);

    states [
        horizontal when orientation == Orientation.horizontal: {
            root.min-height: root.overall-thickness;
            line.height: root.line-thickness;
            line.width: root.width;
            root.horizontal-stretch: 100%;
            root.vertical-stretch: 0%;
        }
        vertical when orientation == Orientation.vertical: {
            root.min-width: root.overall-thickness;
            line.width: root.line-thickness;
            line.height: root.height;
            root.vertical-stretch: 100%;
            root.horizontal-stretch: 0%;
        }
    ]

    line := Rectangle {
        background: Palette.border;
        border-radius: line-thickness / 2;
    }
}

component Undoable inherits HorizontalBox {
    callback undo-clicked <=> undo.clicked;

    @children

    undo := Button {
        icon: @image-url("icons/edit-undo-symbolic.svg");
        colorize-icon: true;
        icon-size: 1.2rem;
        height: self.width;
    }
}

component IntLineEdit inherits LineEdit {
    in-out property <int> value;

    input-type: number;
    text: value;

    changed value => {
        if (!self.has-focus) {
            self.text = value;
        }
    }

    changed text => {
        root.value = self.text.to-float();
    }
}

export component SettingsPage {
    width: 800px;
    height: 600px;
    forward-focus: shortcut-handler;

    callback close;

    ScrollView {
        GridBox {
            width: 75%;
            padding-top: StyleMetrics.layout-padding * 4;
            spacing-horizontal: 100px;
            spacing-vertical: 0px;

            Row {
                Text {
                    text: "Settings";
                    font-size: 3rem;
                    font-weight: 800;
                }
            }

            Row {
                Separator {
                    colspan: 2;
                }
            }

            Row {
                Text {
                    text: "Theme";
                    font-size: 1.1rem;
                    vertical-alignment: center;
                }

                Undoable {
                    undo-clicked => {
                        Settings.reset("theme");
                    }

                    ComboBox {
                        in-out property <ColorScheme> color-scheme <=> Palette.color-scheme;

                        model: ["System", "Dark", "Light"];
                        current-value: {
                            if color-scheme == ColorScheme.dark {
                                "Dark"
                            } else if color-scheme == ColorScheme.light {
                                "Light"
                            } else {
                                "System"
                            }
                        };

                        changed color-scheme => {
                            if color-scheme == ColorScheme.dark {
                                self.current-value = "Dark";
                            } else if color-scheme == ColorScheme.light {
                                self.current-value = "Light";
                            } else {
                                self.current-value = "System";
                            }
                        }

                        changed current-value => {
                            if self.current-value == "Dark" {
                                color-scheme = ColorScheme.dark;
                            } else if self.current-value == "Light" {
                                color-scheme = ColorScheme.light;
                            } else {
                                color-scheme = ColorScheme.unknown;
                            }
                        }

                        selected(current-value) => {
                            Settings.sync-settings();
                        }
                    }
                }
            }

            Row {
                Separator {
                    colspan: 2;
                }
            }

            Row {
                Text {
                    text: "MyStudio";
                    font-size: 1.5rem;
                }
            }

            Row {
                Text {
                    text: "Email";
                    font-size: 1.1rem;
                    vertical-alignment: center;
                }

                Undoable {
                    undo-clicked => {
                        Settings.reset("my-studio.email");
                    }

                    LineEdit {
                        text <=> Settings.my-studio.email;
                        preferred-width: 300px;

                        edited => {
                            Settings.sync-settings();
                        }
                    }
                }
            }

            Row {
                Text {
                    text: "Company ID";
                    font-size: 1.1rem;
                    vertical-alignment: center;
                }

                Undoable {
                    undo-clicked => {
                        Settings.reset("my-studio.company-id");
                    }

                    LineEdit {
                        text <=> Settings.my-studio.company-id;

                        edited => {
                            Settings.sync-settings();
                        }
                    }
                }
            }

            Row {
                Separator {
                    colspan: 2;
                }
            }

            Row {
                Text {
                    text: "Student data spreadsheet";
                    font-size: 1.5rem;
                }
            }

            Row {
                Text {
                    text: "Filepath";
                    font-size: 1.1rem;
                    vertical-alignment: center;
                }

                Undoable {
                    undo-clicked => {
                        Settings.reset("student-data.filepath");
                    }

                    LineEdit {
                        text <=> Settings.student-data.filepath;
                        preferred-width: 300px;

                        edited => {
                            Settings.sync-settings();
                        }
                    }
                }
            }

            Row {
                Text {
                    text: "Sheet name";
                    font-size: 1.1rem;
                    vertical-alignment: center;
                }

                Undoable {
                    undo-clicked => {
                        Settings.reset("student-data.sheet-name");
                    }

                    LineEdit {
                        text <=> Settings.student-data.sheet-name;
                        preferred-width: 300px;

                        edited => {
                            Settings.sync-settings();
                        }
                    }
                }
            }

            Row {
                Text {
                    text: "Name column index";
                    font-size: 1.1rem;
                    vertical-alignment: center;
                }

                Undoable {
                    undo-clicked => {
                        Settings.reset("student-data.name-column");
                    }

                    IntLineEdit {
                        value <=> Settings.student-data.name-column;
                        preferred-width: 300px;

                        edited => {
                            Settings.sync-settings();
                        }
                    }
                }
            }

            Row {
                Text {
                    text: "ID column index";
                    font-size: 1.1rem;
                    vertical-alignment: center;
                }

                Undoable {
                    undo-clicked => {
                        Settings.reset("student-data.id-column");
                    }

                    IntLineEdit {
                        value <=> Settings.student-data.id-column;
                        preferred-width: 300px;

                        edited => {
                            Settings.sync-settings();
                        }
                    }
                }
            }

            Row {
                Text {
                    text: "Immediate sign-in column";
                    font-size: 1.1rem;
                    vertical-alignment: center;
                }

                Undoable {
                    undo-clicked => {
                        Settings.reset("student-data.immediate-sign-in-column");
                    }

                    IntLineEdit {
                        value <=> Settings.student-data.immediate-sign-in-column;
                        preferred-width: 300px;

                        edited => {
                            Settings.sync-settings();
                        }
                    }
                }
            }

            Row {
                Text {
                    text: "Immediate sign-in enabled symbol";
                    font-size: 1.1rem;
                    vertical-alignment: center;
                }

                Undoable {
                    undo-clicked => {
                        Settings.reset("student-data.immediate-sign-in-enabled-symbol");
                    }

                    LineEdit {
                        text <=> Settings.student-data.immediate-sign-in-enabled-symbol;
                        preferred-width: 300px;

                        edited => {
                            Settings.sync-settings();
                        }
                    }
                }
            }
        }
    }

    Rectangle {
        x: root.width - self.width - StyleMetrics.layout-padding;
        y: StyleMetrics.layout-padding;
        width: 40px;
        height: 40px;
        border-width: 2px;
        border-color: Palette.border;

        Image {
            source: @image-url("icons/window-close-symbolic.svg");
            colorize: Palette.control-foreground;
            width: parent.width;
            height: parent.height;
        }

        TouchArea {
            clicked => {
                close();
            }
        }
    }

    Button {
        text: "Reset All";
        x: root.width - self.width - StyleMetrics.layout-padding;
        y: root.height - self.height - StyleMetrics.layout-padding;

        clicked => {
            reset-all-popup.show();
        }
    }

    reset-all-popup := PopupWindow {
        x: root.width / 2 - background.width / 2;
        y: root.height / 2 - background.height / 2;

        background := Rectangle {
            background: Palette.background;
            border-color: Palette.border;
            border-width: 3px;
            border-radius: 10px;
            width: dialog.width + StyleMetrics.layout-padding * 2;
            height: dialog.height + StyleMetrics.layout-padding * 2;
        }

        dialog := Dialog {
            Text {
                text: "Reset all settings to their defaults?";
            }

            StandardButton {
                kind: yes;
                clicked => {
                    Settings.reset-all();
                }
            }

            StandardButton {
                kind: no;
            }
        }
    }

    shortcut-handler := FocusScope {
        key-released(event) => {
            if event.text == Key.Escape {
                close();
                accept
            }
            reject
        }
    }
}
