import { Button, ComboBox, GridBox, HorizontalBox, LineEdit, Palette, ScrollView, StandardButton, StyleMetrics } from "std-widgets.slint";

export enum Theme {
    system,
    dark,
    light,
}

component Separator {
    in property <Orientation> orientation: horizontal;
    property <length> overall-thickness: max(10px, 1phx);
    property <length> line-thickness: max(1.2px, 1phx);

    states [
        horizontal when orientation == Orientation.horizontal: {
            root.min-height: root.overall-thickness;
            line.height: root.line-thickness;
            line.width: root.width;
            root.horizontal-stretch: 100%;
            root.vertical-stretch: 0%;
        }
        vertical when orientation == Orientation.vertical: {
            root.min-width: root.overall-thickness;
            line.width: root.line-thickness;
            line.height: root.height;
            root.vertical-stretch: 100%;
            root.horizontal-stretch: 0%;
        }
    ]

    line := Rectangle {
        background: Palette.border;
        border-radius: line-thickness / 2;
    }
}

component Undoable inherits HorizontalBox {
    alignment: start;

    callback undo-clicked <=> undo.clicked;

    @children

    undo := Button {
        icon: @image-url("icons/edit-undo-symbolic.svg");
        colorize-icon: true;
        height: self.width;
    }
}

export global Settings {
    callback reset-all;

    in-out property <Theme> theme;
    callback changed-theme;
    callback reset-theme;

    in-out property <string> my-studio-email;
    callback changed-my-studio-email;
    callback reset-my-studio-email;

    in-out property <string> my-studio-company-id;
    callback changed-my-studio-company-id;
    callback reset-my-studio-company-id;

    in-out property <string> student-data-filepath;
    callback changed-student-data-filepath;
    callback reset-student-data-filepath;

    in-out property <string> student-data-sheet-name;
    callback changed-student-data-sheet-name;
    callback reset-student-data-sheet-name;

    in-out property <int> student-data-name-column;
    callback changed-student-data-name-column;
    callback reset-student-data-name-column;

    in-out property <int> student-data-id-column;
    callback changed-student-data-id-column;
    callback reset-student-data-id-column;

    in-out property <int> student-data-immediate-sign-in-column;
    callback changed-student-data-immediate-sign-in-column;
    callback reset-student-data-immediate-sign-in-column;

    in-out property <string> student-data-immediate-sign-in-enabled-symbol;
    callback changed-student-data-immediate-sign-in-enabled-symbol;
    callback reset-student-data-immediate-sign-in-enabled-symbol;
}

export component SettingsPage {
    width: 800px;
    height: 600px;
    forward-focus: shortcut-handler;

    callback close;

    ScrollView {
        GridBox {
            width: 75%;
            padding-top: StyleMetrics.layout-padding * 4;
            spacing-horizontal: 100px;

            Row {
                Text {
                    text: "Settings";
                    font-size: 25pt;
                    font-weight: 800;
                }
            }

            Row {
                Separator {
                    colspan: 2;
                }
            }

            Row {
                Text {
                    text: "Theme";
                    font-size: 10pt;
                }

                Undoable {
                    undo-clicked => {
                        Settings.reset-theme();
                    }

                    ComboBox {
                        model: ["System", "Dark", "Light"];
                        current-value: theme-value;

                        property <string> theme-value: {
                            if Settings.theme == Theme.dark {
                                return "Dark";
                            } else if Settings.theme == Theme.light {
                                return "Light";
                            } else {
                                return "System";
                            }
                        }
                        selected(current-value) => {
                            if current-value == "Dark" {
                                Settings.theme = Theme.dark;
                            } else if current-value == "Light" {
                                Settings.theme = Theme.light;
                            } else {
                                Settings.theme = Theme.system;
                            }
                            Settings.changed-theme();
                        }
                    }
                }
            }

            Row {
                Separator {
                    colspan: 2;
                }
            }

            Row {
                Text {
                    text: "MyStudio";
                    font-size: 12pt;
                }
            }

            Row {
                Text {
                    text: "Email";
                    font-size: 10pt;
                }

                Undoable {
                    undo-clicked => {
                        Settings.reset-my-studio-email();
                    }

                    LineEdit {
                        text: Settings.my-studio-email;
                        preferred-width: 300px;

                        edited(text) => {
                            Settings.my-studio-email = text;
                            Settings.changed-my-studio-email();
                        }
                    }
                }
            }

            Row {
                Text {
                    text: "Company ID";
                    font-size: 10pt;
                }

                Undoable {
                    undo-clicked => {
                        Settings.reset-my-studio-company-id();
                    }

                    LineEdit {
                        text: Settings.my-studio-company-id;

                        edited(text) => {
                            Settings.my-studio-company-id = text;
                            Settings.changed-my-studio-company-id();
                        }
                    }
                }
            }

            Row {
                Separator {
                    colspan: 2;
                }
            }

            Row {
                Text {
                    text: "Student Data Spreadsheet";
                    font-size: 12pt;
                }
            }

            Row {
                Text {
                    text: "Filename";
                    font-size: 10pt;
                }

                Undoable {
                    undo-clicked => {
                        Settings.reset-student-data-filepath();
                    }

                    LineEdit {
                        text: Settings.student-data-filepath;
                        preferred-width: 300px;

                        edited(text) => {
                            Settings.student-data-filepath = text;
                            Settings.changed-student-data-filepath();
                        }
                    }
                }
            }

            Row {
                Text {
                    text: "Sheet name";
                    font-size: 10pt;
                }

                Undoable {
                    undo-clicked => {
                        Settings.reset-student-data-sheet-name();
                    }

                    LineEdit {
                        text: Settings.student-data-sheet-name;
                        preferred-width: 300px;

                        edited(text) => {
                            Settings.student-data-sheet-name = text;
                            Settings.changed-student-data-sheet-name();
                        }
                    }
                }
            }

            Row {
                Text {
                    text: "Name column index";
                    font-size: 10pt;
                }

                Undoable {
                    undo-clicked => {
                        Settings.reset-student-data-name-column();
                    }

                    LineEdit {
                        text: Settings.student-data-name-column;
                        input-type: number;
                        preferred-width: 300px;

                        edited(text) => {
                            Settings.student-data-name-column = text.to-float();
                            Settings.changed-student-data-name-column();
                        }
                    }
                }
            }

            Row {
                Text {
                    text: "ID column index";
                    font-size: 10pt;
                }

                Undoable {
                    undo-clicked => {
                        Settings.reset-student-data-id-column();
                    }

                    LineEdit {
                        text: Settings.student-data-id-column;
                        input-type: number;
                        preferred-width: 300px;

                        edited(text) => {
                            Settings.student-data-id-column = text.to-float();
                            Settings.changed-student-data-id-column();
                        }
                    }
                }
            }

            Row {
                Text {
                    text: "Immediate sign-in column";
                    font-size: 10pt;
                }

                Undoable {
                    undo-clicked => {
                        Settings.reset-student-data-immediate-sign-in-column();
                    }

                    LineEdit {
                        text: Settings.student-data-immediate-sign-in-column;
                        input-type: number;
                        preferred-width: 300px;

                        edited(text) => {
                            Settings.student-data-immediate-sign-in-column = text.to-float();
                            Settings.changed-student-data-immediate-sign-in-column();
                        }
                    }
                }
            }

            Row {
                Text {
                    text: "Immediate sign-in enabled symbol";
                    font-size: 10pt;
                }

                Undoable {
                    undo-clicked => {
                        Settings.reset-student-data-immediate-sign-in-enabled-symbol();
                    }

                    LineEdit {
                        text: Settings.student-data-immediate-sign-in-enabled-symbol;
                        preferred-width: 300px;

                        edited(text) => {
                            Settings.student-data-immediate-sign-in-enabled-symbol = text;
                            Settings.changed-student-data-immediate-sign-in-enabled-symbol();
                        }
                    }
                }
            }
        }
    }

    Rectangle {
        x: root.width - self.width - self.padding;
        y: self.padding;
        width: 40px;
        height: 40px;
        padding: StyleMetrics.layout-padding;
        border-width: 2px;
        border-color: Palette.border;

        Image {
            source: @image-url("icons/window-close-symbolic.svg");
            colorize: Palette.control-foreground;
            width: parent.width;
            height: parent.height;
        }

        TouchArea {
            clicked => {
                close();
            }
        }
    }

    Button {
        text: "Reset All";
        x: root.width - self.width - self.padding;
        y: root.height - self.height - self.padding;
        padding: StyleMetrics.layout-padding;

        clicked => {
            reset-all-popup.show();
        }
    }

    reset-all-popup := PopupWindow {
        x: root.width / 2 - background.width / 2;
        y: root.height / 2 - background.height / 2;

        background := Rectangle {
            background: Palette.background;
            border-color: Palette.border;
            border-width: 3px;
            border-radius: 10px;
            width: dialog.width + StyleMetrics.layout-padding * 2;
            height: dialog.height + StyleMetrics.layout-padding * 2;
        }

        dialog := Dialog {
            Text {
                text: "Reset all settings to their defaults?";
            }

            StandardButton {
                kind: yes;
                clicked => {
                    Settings.reset-all();
                }
            }

            StandardButton {
                kind: no;
            }
        }
    }

    shortcut-handler := FocusScope {
        key-released(event) => {
            if event.text == Key.Escape {
                close();
                accept
            }
            reject
        }
    }
}
